/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.10.0
 *
 * Project: 'Project.Debug+PIC32CM1216MC00048' 
 * Target:  'Debug+PIC32CM1216MC00048' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "pic32c.h"



#endif /* RTE_COMPONENTS_H */
